export const products = [
  // Row 1 - Electronics (4 products)
  {
    id: 1,
    title: "Sony WH-1000XM4 Wireless Headphones",
    price: 349.99,
    originalPrice: 399.99,
    discountPercentage: 12,
    category: "Electronics",
    subCategory: "Audio",
    description: "Industry-leading noise cancellation with exceptional sound quality. 30-hour battery life with quick charging. Touch controls and voice assistant support.",
    rating: 4.8,
    reviews: 2543,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&auto=format",
    badge: "Best Seller",
    stock: 45,
    brand: "Sony",
    colors: ["Black", "Silver", "Blue"],
    features: ["Noise Cancelling", "30hr Battery", "Touch Control", "Voice Assistant"]
  },
  {
    id: 2,
    title: "Apple Watch Series 9 GPS 41mm",
    price: 429.00,
    originalPrice: 499.00,
    discountPercentage: 14,
    category: "Wearables",
    subCategory: "Smart Watches",
    description: "Stay connected with the most advanced Apple Watch yet. Features S9 chip, double tap gesture, and brighter display. Track your fitness and health.",
    rating: 4.9,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=300&auto=format",
    badge: "New",
    stock: 32,
    brand: "Apple",
    colors: ["Midnight", "Starlight", "Silver"],
    features: ["GPS", "Heart Monitor", "Water Resistant", "Always-On Display"]
  },
  {
    id: 3,
    title: "MacBook Pro 14-inch M3 Pro",
    price: 1999.00,
    originalPrice: 2199.00,
    discountPercentage: 9,
    category: "Electronics",
    subCategory: "Laptops",
    description: "The most advanced Mac laptop for demanding workflows. M3 Pro chip, 18GB unified memory, 512GB SSD. Liquid Retina XDR display.",
    rating: 4.9,
    reviews: 3210,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&auto=format",
    badge: "Premium",
    stock: 18,
    brand: "Apple",
    colors: ["Space Gray", "Silver"],
    features: ["M3 Pro Chip", "18GB RAM", "512GB SSD", "Liquid Retina XDR"]
  },
  {
    id: 4,
    title: "iPad Pro 12.9-inch M2",
    price: 1099.00,
    originalPrice: 1199.00,
    discountPercentage: 8,
    category: "Electronics",
    subCategory: "Tablets",
    description: "Ultimate iPad experience with M2 chip, Liquid Retina XDR display, and pro cameras. Perfect for creatives and professionals.",
    rating: 4.8,
    reviews: 1542,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=300&auto=format",
    badge: "Editors' Choice",
    stock: 23,
    brand: "Apple",
    colors: ["Space Gray", "Silver"],
    features: ["M2 Chip", "Liquid Retina XDR", "5G", "Face ID"]
  },
  
  // Row 2 - Fashion & Accessories (4 products)
  {
    id: 5,
    title: "The North Face Borealis Backpack",
    price: 89.99,
    originalPrice: 109.99,
    discountPercentage: 18,
    category: "Accessories",
    subCategory: "Bags",
    description: "Versatile backpack with FlexVent suspension system for maximum comfort. Laptop sleeve and multiple pockets for organization.",
    rating: 4.7,
    reviews: 3241,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&auto=format",
    badge: "Popular",
    stock: 67,
    brand: "The North Face",
    colors: ["Black", "Grey", "Navy", "Green"],
    features: ["Laptop Sleeve", "Water Resistant", "FlexVent Suspension", "Multiple Pockets"]
  },
  {
    id: 6,
    title: "Nike Air Zoom Pegasus 40",
    price: 129.99,
    originalPrice: 149.99,
    discountPercentage: 13,
    category: "Footwear",
    subCategory: "Running Shoes",
    description: "Responsive running shoes with Zoom Air units. Engineered for comfort mile after mile with breathable mesh upper.",
    rating: 4.8,
    reviews: 4567,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&auto=format",
    badge: "Trending",
    stock: 89,
    brand: "Nike",
    colors: ["Black/White", "Blue", "Red", "Grey"],
    features: ["Zoom Air", "Breathable Mesh", "Responsive Cushioning", "Durable Outsole"]
  },
  {
    id: 7,
    title: "Ray-Ban Aviator Classic",
    price: 153.00,
    originalPrice: 179.00,
    discountPercentage: 15,
    category: "Accessories",
    subCategory: "Sunglasses",
    description: "Iconic aviator design with gradient lenses. 100% UV protection and lightweight metal frame for all-day comfort.",
    rating: 4.8,
    reviews: 2189,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=300&auto=format",
    badge: "Classic",
    stock: 42,
    brand: "Ray-Ban",
    colors: ["Gold/Green", "Silver/Blue", "Black"],
    features: ["UV Protection", "Gradient Lenses", "Metal Frame", "Classic Design"]
  },
  {
    id: 8,
    title: "Casio G-Shock Digital Watch",
    price: 99.99,
    originalPrice: 129.99,
    discountPercentage: 23,
    category: "Wearables",
    subCategory: "Watches",
    description: "Tough, shock-resistant digital watch with stopwatch, timer, and world time. Water resistant to 200m.",
    rating: 4.7,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=300&auto=format",
    badge: "Best Value",
    stock: 56,
    brand: "Casio",
    colors: ["Black", "White", "Red"],
    features: ["Shock Resistant", "200m Water Resistant", "Stopwatch", "World Time"]
  },
  
  // Row 3 - Home & Lifestyle (4 products)
  {
    id: 9,
    title: "Instant Pot Duo 7-in-1",
    price: 89.99,
    originalPrice: 119.99,
    discountPercentage: 25,
    category: "Home",
    subCategory: "Kitchen Appliances",
    description: "Electric pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer in one appliance.",
    rating: 4.8,
    reviews: 8921,
    image: "https://images.unsplash.com/photo-1544237510-524c8c8a044c?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1544237510-524c8c8a044c?w=300&auto=format",
    badge: "Bestseller",
    stock: 103,
    brand: "Instant Pot",
    colors: ["Stainless Steel", "Black"],
    features: ["7-in-1 Functions", "Programmable", "Dishwasher Safe", "Food Grade Materials"]
  },
  {
    id: 10,
    title: "Dyson V15 Detect Vacuum",
    price: 699.99,
    originalPrice: 749.99,
    discountPercentage: 7,
    category: "Home",
    subCategory: "Cleaning",
    description: "Powerful cordless vacuum with laser detection and intelligent cleaning. Captures 99.99% of particles.",
    rating: 4.9,
    reviews: 1543,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=300&auto=format",
    badge: "Premium",
    stock: 27,
    brand: "Dyson",
    colors: ["Yellow/Nickel"],
    features: ["Laser Detection", "60min Run Time", "HEPA Filtering", "LCD Screen"]
  },
  {
    id: 11,
    title: "Sonos One SL Speaker",
    price: 199.00,
    originalPrice: 229.00,
    discountPercentage: 13,
    category: "Audio",
    subCategory: "Speakers",
    description: "Powerful wireless speaker with rich sound. Pair with another for stereo or home theater setup.",
    rating: 4.8,
    reviews: 2341,
    image: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1543512214-318c7553f230?w=300&auto=format",
    badge: "Top Rated",
    stock: 38,
    brand: "Sonos",
    colors: ["Black", "White"],
    features: ["WiFi", "Multi-room Audio", "Voice Compatible", "Moisture Resistant"]
  },
  {
    id: 12,
    title: "Kindle Paperwhite",
    price: 139.99,
    originalPrice: 159.99,
    discountPercentage: 12,
    category: "Electronics",
    subCategory: "E-Readers",
    description: "Waterproof e-reader with 6.8\" display and adjustable warm light. Weeks of battery life.",
    rating: 4.8,
    reviews: 5678,
    image: "https://images.unsplash.com/photo-1592496001020-31c295dcd8f0?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1592496001020-31c295dcd8f0?w=300&auto=format",
    badge: "Editors' Choice",
    stock: 74,
    brand: "Amazon",
    colors: ["Black", "Agave Green"],
    features: ["Waterproof", "Adjustable Warm Light", "Weeks Battery", "32GB Storage"]
  },
  
  // Row 4 - More Electronics (4 products)
  {
    id: 13,
    title: "Samsung 32\" Smart Monitor",
    price: 279.99,
    originalPrice: 329.99,
    discountPercentage: 15,
    category: "Electronics",
    subCategory: "Monitors",
    description: "4K UHD smart monitor with streaming apps and workspace hub. Built-in speakers and remote included.",
    rating: 4.7,
    reviews: 1234,
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=300&auto=format",
    badge: "Smart Choice",
    stock: 31,
    brand: "Samsung",
    colors: ["Black"],
    features: ["4K UHD", "Smart TV Apps", "USB-C", "Built-in Speakers"]
  },
  {
    id: 14,
    title: "Canon EOS R6 Mark II",
    price: 2499.00,
    originalPrice: 2699.00,
    discountPercentage: 7,
    category: "Electronics",
    subCategory: "Cameras",
    description: "Full-frame mirrorless camera with 24.2MP sensor and 4K video. Advanced autofocus and image stabilization.",
    rating: 4.9,
    reviews: 876,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=300&auto=format",
    badge: "Pro Choice",
    stock: 12,
    brand: "Canon",
    colors: ["Black"],
    features: ["24.2MP Sensor", "4K Video", "IBIS", "Dual Pixel AF"]
  },
  {
    id: 15,
    title: "Bose QuietComfort Earbuds II",
    price: 279.00,
    originalPrice: 299.00,
    discountPercentage: 7,
    category: "Audio",
    subCategory: "Earbuds",
    description: "World-class noise cancelling earbuds with customizable sound and secure fit. 6 hours of battery life.",
    rating: 4.8,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=300&auto=format",
    badge: "Top Rated",
    stock: 54,
    brand: "Bose",
    colors: ["Black", "White"],
    features: ["Noise Cancelling", "Customizable Sound", "Secure Fit", "Wireless Charging"]
  },
  {
    id: 16,
    title: "GoPro HERO12 Black",
    price: 399.99,
    originalPrice: 449.99,
    discountPercentage: 11,
    category: "Electronics",
    subCategory: "Cameras",
    description: "Waterproof action camera with 5.3K video and HyperSmooth stabilization. Perfect for adventures.",
    rating: 4.8,
    reviews: 2345,
    image: "https://images.unsplash.com/photo-1526378800651-c1d9b95f4cf3?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1526378800651-c1d9b95f4cf3?w=300&auto=format",
    badge: "Adventure Ready",
    stock: 41,
    brand: "GoPro",
    colors: ["Black"],
    features: ["5.3K Video", "Waterproof", "HyperSmooth", "Voice Control"]
  },
  
  // Row 5 - Fashion (4 products)
  {
    id: 17,
    title: "Levi's 501 Original Jeans",
    price: 79.99,
    originalPrice: 98.00,
    discountPercentage: 18,
    category: "Fashion",
    subCategory: "Jeans",
    description: "Classic straight-fit jeans made from high-quality denim. The original since 1873.",
    rating: 4.7,
    reviews: 4321,
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=300&auto=format",
    badge: "Classic",
    stock: 112,
    brand: "Levi's",
    colors: ["Blue", "Black", "Grey"],
    features: ["100% Cotton", "Button Fly", "5-Pocket Style", "Straight Fit"]
  },
  {
    id: 18,
    title: "Patagonia Better Sweater",
    price: 139.00,
    originalPrice: 159.00,
    discountPercentage: 13,
    category: "Fashion",
    subCategory: "Sweaters",
    description: "Warm, fair trade certified fleece sweater made from recycled materials. Perfect for layering.",
    rating: 4.8,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=300&auto=format",
    badge: "Sustainable",
    stock: 38,
    brand: "Patagonia",
    colors: ["Navy", "Gray", "Green", "Burgundy"],
    features: ["Recycled Materials", "Fair Trade", "Quarter-Zip", "Machine Washable"]
  },
  {
    id: 19,
    title: "Timberland Premium Boots",
    price: 198.00,
    originalPrice: 228.00,
    discountPercentage: 13,
    category: "Footwear",
    subCategory: "Boots",
    description: "Waterproof leather boots with padded collar for comfort. Durable and stylish for any weather.",
    rating: 4.8,
    reviews: 3210,
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=300&auto=format",
    badge: "Iconic",
    stock: 47,
    brand: "Timberland",
    colors: ["Wheat", "Black", "Brown"],
    features: ["Waterproof", "Leather Upper", "Padded Collar", "Rubber Outsole"]
  },
  {
    id: 20,
    title: "Adidas Ultraboost 23",
    price: 189.99,
    originalPrice: 219.99,
    discountPercentage: 14,
    category: "Footwear",
    subCategory: "Running Shoes",
    description: "Responsive running shoes with Boost cushioning and Primeknit upper. Energy return with every step.",
    rating: 4.8,
    reviews: 2876,
    image: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=300&auto=format",
    badge: "Energy",
    stock: 65,
    brand: "Adidas",
    colors: ["Black/White", "Blue", "Grey", "Green"],
    features: ["Boost Cushioning", "Primeknit Upper", "Stretch Web Outsole", "Continental Rubber"]
  },
  
  // Row 6 - More Accessories (4 products)
  {
    id: 21,
    title: "Bellroy Note Sleeve Wallet",
    price: 89.00,
    originalPrice: 99.00,
    discountPercentage: 10,
    category: "Accessories",
    subCategory: "Wallets",
    description: "Slim leather wallet with quick access to cards and notes. Premium quality and thoughtful design.",
    rating: 4.8,
    reviews: 1432,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=300&auto=format",
    badge: "Minimalist",
    stock: 78,
    brand: "Bellroy",
    colors: ["Black", "Brown", "Navy", "Tan"],
    features: ["Premium Leather", "Quick Access", "Slim Design", "3-Year Warranty"]
  },
  {
    id: 22,
    title: "Herschel Supply Co. Novel Duffle",
    price: 79.99,
    originalPrice: 99.99,
    discountPercentage: 20,
    category: "Accessories",
    subCategory: "Bags",
    description: "Classic duffle bag with striped liner and pebbled leather pulls. Perfect for weekend trips.",
    rating: 4.7,
    reviews: 1654,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=300&auto=format",
    badge: "Travel Ready",
    stock: 43,
    brand: "Herschel",
    colors: ["Black", "Navy", "Olive"],
    features: ["40L Capacity", "Pebbled Leather Pulls", "Striped Liner", "Adjustable Strap"]
  },
  {
    id: 23,
    title: "Fjällräven Kånken Laptop 15\"",
    price: 99.00,
    originalPrice: 115.00,
    discountPercentage: 14,
    category: "Accessories",
    subCategory: "Bags",
    description: "Classic Swedish backpack with padded laptop compartment. Durable Vinylon F material.",
    rating: 4.8,
    reviews: 1987,
    image: "https://images.unsplash.com/photo-1581605405669-bcdf4b2e8c9b?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1581605405669-bcdf4b2e8c9b?w=300&auto=format",
    badge: "Iconic",
    stock: 34,
    brand: "Fjällräven",
    colors: ["Ox Red", "Navy", "Graphite", "Frost Green"],
    features: ["Laptop Sleeve", "Water Resistant", "Adjustable Straps", "Reflective Logo"]
  },
  {
    id: 24,
    title: "Bellroy Classic Backpack",
    price: 149.00,
    originalPrice: 169.00,
    discountPercentage: 12,
    category: "Accessories",
    subCategory: "Bags",
    description: "Premium leather backpack with padded laptop compartment and multiple pockets. Timeless design.",
    rating: 4.9,
    reviews: 987,
    image: "https://images.unsplash.com/photo-1546938576-6e6a64f317cc?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1546938576-6e6a64f317cc?w=300&auto=format",
    badge: "Premium",
    stock: 19,
    brand: "Bellroy",
    colors: ["Black", "Brown", "Navy"],
    features: ["Premium Leather", "Padded Laptop Sleeve", "Multiple Pockets", "Quick Access"]
  },
  
  // Row 7 - Home & Kitchen (4 products)
  {
    id: 25,
    title: "KitchenAid Stand Mixer",
    price: 399.99,
    originalPrice: 449.99,
    discountPercentage: 11,
    category: "Home",
    subCategory: "Kitchen Appliances",
    description: "Iconic stand mixer with 10 speeds and 5-quart stainless steel bowl. Perfect for baking enthusiasts.",
    rating: 4.9,
    reviews: 5432,
    image: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=300&auto=format",
    badge: "Kitchen Essential",
    stock: 27,
    brand: "KitchenAid",
    colors: ["Empire Red", "Artisan Blue", "Black", "White"],
    features: ["10 Speeds", "5-Quart Bowl", "Tilt-Head Design", "Hobart Manufacturing"]
  },
  {
    id: 26,
    title: "Le Creuset Dutch Oven",
    price: 349.00,
    originalPrice: 379.00,
    discountPercentage: 8,
    category: "Home",
    subCategory: "Cookware",
    description: "Enameled cast iron Dutch oven for perfect cooking. Excellent heat retention and distribution.",
    rating: 4.9,
    reviews: 3210,
    image: "https://images.unsplash.com/photo-1584990347445-b41b0a6a3b6f?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1584990347445-b41b0a6a3b6f?w=300&auto=format",
    badge: "Heirloom Quality",
    stock: 21,
    brand: "Le Creuset",
    colors: ["Flame", "Marseille", "Cherry", "Oyster"],
    features: ["Enameled Cast Iron", "Even Heating", "Easy Clean", "Lifetime Warranty"]
  },
  {
    id: 27,
    title: "Nespresso Vertuo Coffee Maker",
    price: 169.99,
    originalPrice: 199.99,
    discountPercentage: 15,
    category: "Home",
    subCategory: "Coffee Makers",
    description: "Coffee and espresso maker with Centrifusion technology. Brews multiple cup sizes.",
    rating: 4.7,
    reviews: 2987,
    image: "https://images.unsplash.com/photo-1565791380713-1756b9a05343?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1565791380713-1756b9a05343?w=300&auto=format",
    badge: "Morning Essential",
    stock: 52,
    brand: "Nespresso",
    colors: ["Black", "Red", "Silver"],
    features: ["Centrifusion Technology", "Multiple Sizes", "Fast Heat-Up", "Used Capsule Container"]
  },
  {
    id: 28,
    title: "Ninja Foodi Pressure Cooker",
    price: 179.99,
    originalPrice: 219.99,
    discountPercentage: 18,
    category: "Home",
    subCategory: "Kitchen Appliances",
    description: "Pressure cooker and air fryer in one. Tender and crispy meals in minutes.",
    rating: 4.8,
    reviews: 4321,
    image: "https://images.unsplash.com/photo-1584269600416-0d5f9c5c2f8b?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1584269600416-0d5f9c5c2f8b?w=300&auto=format",
    badge: "Versatile",
    stock: 43,
    brand: "Ninja",
    colors: ["Stainless Steel", "Black"],
    features: ["Pressure Cooker", "Air Fryer", "TenderCrisp Technology", "8-in-1 Functions"]
  },
  
  // Row 8 - Fitness & Outdoors (4 products)
  {
    id: 29,
    title: "Peloton Bike+",
    price: 2495.00,
    originalPrice: 2695.00,
    discountPercentage: 7,
    category: "Fitness",
    subCategory: "Exercise Bikes",
    description: "Immersive indoor cycling experience with rotating screen and live classes. Auto-follow resistance.",
    rating: 4.9,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1574688929568-3a8b9be6e1f9?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1574688929568-3a8b9be6e1f9?w=300&auto=format",
    badge: "Premium Fitness",
    stock: 8,
    brand: "Peloton",
    colors: ["Black"],
    features: ["Rotating Screen", "Auto-Follow", "Live Classes", "High-Fidelity Sound"]
  },
  {
    id: 30,
    title: "Yeti Tundra 45 Cooler",
    price: 299.99,
    originalPrice: 329.99,
    discountPercentage: 9,
    category: "Outdoors",
    subCategory: "Coolers",
    description: "Rotomolded cooler with up to 3 inches of insulation. Keeps ice for days.",
    rating: 4.9,
    reviews: 2543,
    image: "https://images.unsplash.com/photo-1606335006982-99b31a5c6b1b?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1606335006982-99b31a5c6b1b?w=300&auto=format",
    badge: "Adventure Ready",
    stock: 23,
    brand: "Yeti",
    colors: ["White", "Tan", "Blue", "Green"],
    features: ["Rotomolded", "Ice Retention", "Bear-Resistant", "Non-Slip Feet"]
  },
  {
    id: 31,
    title: "Hydro Flask 32oz Water Bottle",
    price: 44.95,
    originalPrice: 49.95,
    discountPercentage: 10,
    category: "Accessories",
    subCategory: "Water Bottles",
    description: "Double-wall vacuum insulated water bottle. Keeps drinks cold for 24 hours or hot for 12.",
    rating: 4.8,
    reviews: 8765,
    image: "https://images.unsplash.com/photo-1597245789418-2e2b6f0a7f9a?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1597245789418-2e2b6f0a7f9a?w=300&auto=format",
    badge: "Essential",
    stock: 156,
    brand: "Hydro Flask",
    colors: ["Black", "White", "Pink", "Blue", "Green"],
    features: ["Double-Wall Insulation", "TempShield Technology", "BPA-Free", "Wide Mouth"]
  },
  {
    id: 32,
    title: "Lululemon The Mat 5mm",
    price: 68.00,
    originalPrice: 78.00,
    discountPercentage: 13,
    category: "Fitness",
    subCategory: "Yoga Mats",
    description: "High-performance yoga mat with polyurethane surface. Natural rubber base for cushioning.",
    rating: 4.8,
    reviews: 1654,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=300&auto=format",
    badge: "Yoga Essential",
    stock: 67,
    brand: "Lululemon",
    colors: ["Black", "Navy", "Purple", "Teal"],
    features: ["Polyurethane Surface", "Natural Rubber Base", "5mm Thickness", "Moisture-Wicking"]
  },
  
  // Row 9 - Beauty & Personal Care (4 products)
  {
    id: 33,
    title: "Dyson Airwrap Complete",
    price: 599.99,
    originalPrice: 649.99,
    discountPercentage: 8,
    category: "Beauty",
    subCategory: "Hair Styling",
    description: "Multi-styler for curling, waving, smoothing and drying without extreme heat.",
    rating: 4.7,
    reviews: 2341,
    image: "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=300&auto=format",
    badge: "Luxury",
    stock: 12,
    brand: "Dyson",
    colors: ["Nickel/Copper", "Vinca Blue/Rosé"],
    features: ["No Extreme Heat", "Multiple Attachments", "Coanda Effect", "Intelligent Heat Control"]
  },
  {
    id: 34,
    title: "Philips Sonicare DiamondClean",
    price: 199.99,
    originalPrice: 229.99,
    discountPercentage: 13,
    category: "Personal Care",
    subCategory: "Oral Care",
    description: "Premium electric toothbrush with multiple cleaning modes and smart sensor technology.",
    rating: 4.8,
    reviews: 4321,
    image: "https://images.unsplash.com/photo-1621786030484-4c855eed4e8f?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1621786030484-4c855eed4e8f?w=300&auto=format",
    badge: "Top Rated",
    stock: 43,
    brand: "Philips",
    colors: ["Black", "White", "Pink"],
    features: ["5 Cleaning Modes", "Smart Sensor", "Pressure Sensor", "Travel Case"]
  },
  {
    id: 35,
    title: "The Ordinary Skincare Set",
    price: 49.99,
    originalPrice: 69.99,
    discountPercentage: 29,
    category: "Beauty",
    subCategory: "Skincare",
    description: "Complete skincare regimen set with cleanser, serum, moisturizer and more.",
    rating: 4.7,
    reviews: 6543,
    image: "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=300&auto=format",
    badge: "Value Set",
    stock: 87,
    brand: "The Ordinary",
    colors: ["One Size"],
    features: ["Complete Routine", "Cruelty-Free", "Vegan", "Fragrance-Free"]
  },
  {
    id: 36,
    title: "GHD Platinum+ Styler",
    price: 249.00,
    originalPrice: 279.00,
    discountPercentage: 11,
    category: "Beauty",
    subCategory: "Hair Styling",
    description: "Predictive straightener that adapts to your hair for optimal styling with less damage.",
    rating: 4.9,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1615487246380-4f9a75f0b7f5?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1615487246380-4f9a75f0b7f5?w=300&auto=format",
    badge: "Professional",
    stock: 23,
    brand: "GHD",
    colors: ["Black", "White"],
    features: ["Predictive Technology", "Ultra-Zone Technology", "Universal Voltage", "Auto Sleep Mode"]
  },
  
  // Row 10 - Gaming & Entertainment (4 products)
  {
    id: 37,
    title: "PlayStation 5 Console",
    price: 499.99,
    originalPrice: 549.99,
    discountPercentage: 9,
    category: "Gaming",
    subCategory: "Consoles",
    description: "Next-gen gaming console with lightning-fast loading and immersive haptic feedback.",
    rating: 4.9,
    reviews: 8765,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=300&auto=format",
    badge: "Next Gen",
    stock: 5,
    brand: "Sony",
    colors: ["White"],
    features: ["4K Gaming", "Ray Tracing", "Haptic Feedback", "Ultra-High Speed SSD"]
  },
  {
    id: 38,
    title: "Xbox Series X",
    price: 499.99,
    originalPrice: 529.99,
    discountPercentage: 6,
    category: "Gaming",
    subCategory: "Consoles",
    description: "Fastest, most powerful Xbox ever with true 4K gaming and 12 teraflops of processing power.",
    rating: 4.8,
    reviews: 5432,
    image: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=300&auto=format",
    badge: "Powerful",
    stock: 7,
    brand: "Microsoft",
    colors: ["Black"],
    features: ["4K Gaming", "120 FPS", "Quick Resume", "Smart Delivery"]
  },
  {
    id: 39,
    title: "Nintendo Switch OLED",
    price: 349.99,
    originalPrice: 379.99,
    discountPercentage: 8,
    category: "Gaming",
    subCategory: "Consoles",
    description: "Hybrid gaming console with vibrant 7-inch OLED screen and enhanced audio.",
    rating: 4.8,
    reviews: 6543,
    image: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?w=300&auto=format",
    badge: "Family Favorite",
    stock: 18,
    brand: "Nintendo",
    colors: ["White", "Neon Red/Blue"],
    features: ["7-inch OLED", "Enhanced Audio", "Wired LAN Port", "64GB Storage"]
  },
  {
    id: 40,
    title: "Logitech G502 X Plus",
    price: 159.99,
    originalPrice: 179.99,
    discountPercentage: 11,
    category: "Gaming",
    subCategory: "Accessories",
    description: "Wireless gaming mouse with LIGHTFORCE hybrid switches and LIGHTSYNC RGB.",
    rating: 4.8,
    reviews: 3210,
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format",
    badge: "Pro Gaming",
    stock: 42,
    brand: "Logitech",
    colors: ["Black", "White"],
    features: ["LIGHTFORCE Switches", "LIGHTSYNC RGB", "HERO 25K Sensor", "Wireless"]
  },
  
  // Row 11 - Books & Media (4 products)
  {
    id: 41,
    title: "Atomic Habits by James Clear",
    price: 16.99,
    originalPrice: 24.99,
    discountPercentage: 32,
    category: "Books",
    subCategory: "Self-Help",
    description: "Tiny Changes, Remarkable Results. The #1 New York Times bestseller.",
    rating: 4.9,
    reviews: 15432,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=300&auto=format",
    badge: "Bestseller",
    stock: 234,
    brand: "James Clear",
    colors: ["Hardcover", "Paperback", "Audiobook"],
    features: ["New York Times Bestseller", "Practical Strategies", "Proven Framework", "Real-Life Stories"]
  },
  {
    id: 42,
    title: "The Creative Act by Rick Rubin",
    price: 21.99,
    originalPrice: 29.99,
    discountPercentage: 27,
    category: "Books",
    subCategory: "Creativity",
    description: "A way of being from the legendary music producer. A beautiful and generous course of study.",
    rating: 4.8,
    reviews: 5432,
    image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=300&auto=format",
    badge: "New Release",
    stock: 87,
    brand: "Rick Rubin",
    colors: ["Hardcover", "Audiobook"],
    features: ["Philosophical", "Inspirational", "Artist Wisdom", "Creative Practice"]
  },
  {
    id: 43,
    title: "AirPods Max",
    price: 549.00,
    originalPrice: 599.00,
    discountPercentage: 8,
    category: "Audio",
    subCategory: "Headphones",
    description: "Over-ear headphones with computational audio and adaptive EQ for personal sound.",
    rating: 4.7,
    reviews: 3210,
    image: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=300&auto=format",
    badge: "Premium Audio",
    stock: 14,
    brand: "Apple",
    colors: ["Space Gray", "Silver", "Green", "Sky Blue", "Pink"],
    features: ["Computational Audio", "Adaptive EQ", "Active Noise Cancellation", "Spatial Audio"]
  },
  {
    id: 44,
    title: "Samsung Galaxy S23 Ultra",
    price: 1199.99,
    originalPrice: 1299.99,
    discountPercentage: 8,
    category: "Electronics",
    subCategory: "Smartphones",
    description: "Premium smartphone with 200MP camera and built-in S Pen. Powerful performance.",
    rating: 4.8,
    reviews: 4321,
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=300&auto=format",
    badge: "Flagship",
    stock: 21,
    brand: "Samsung",
    colors: ["Phantom Black", "Green", "Lavender", "Cream"],
    features: ["200MP Camera", "S Pen", "Snapdragon 8 Gen 2", "5000mAh Battery"]
  },
  
  // Row 12 - More Products (6 products to reach 50 total)
  {
    id: 45,
    title: "DJI Mini 3 Pro Drone",
    price: 669.00,
    originalPrice: 719.00,
    discountPercentage: 7,
    category: "Electronics",
    subCategory: "Drones",
    description: "Lightweight drone with 4K HDR video and obstacle sensing. Under 249g for easy travel.",
    rating: 4.9,
    reviews: 1876,
    image: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=300&auto=format",
    badge: "Fly Cam",
    stock: 16,
    brand: "DJI",
    colors: ["Gray"],
    features: ["4K HDR Video", "Obstacle Sensing", "<249g", "35min Flight Time"]
  },
  {
    id: 46,
    title: "Breville Barista Express",
    price: 649.99,
    originalPrice: 699.99,
    discountPercentage: 7,
    category: "Home",
    subCategory: "Coffee Makers",
    description: "Semi-automatic espresso machine with built-in grinder for fresh coffee every time.",
    rating: 4.8,
    reviews: 2876,
    image: "https://images.unsplash.com/photo-1517914309065-16472f47b7e2?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1517914309065-16472f47b7e2?w=300&auto=format",
    badge: "Barista Quality",
    stock: 12,
    brand: "Breville",
    colors: ["Stainless Steel"],
    features: ["Built-in Grinder", "Digital Temperature Control", "Hot Water Dispenser", "Steam Wand"]
  },
  {
    id: 47,
    title: "Marshall Stanmore II Speaker",
    price: 299.99,
    originalPrice: 349.99,
    discountPercentage: 14,
    category: "Audio",
    subCategory: "Speakers",
    description: "Classic Marshall design with modern Bluetooth technology. Rich, immersive sound.",
    rating: 4.8,
    reviews: 2341,
    image: "https://images.unsplash.com/photo-1545455420-54a4a27a7e1b?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1545455420-54a4a27a7e1b?w=300&auto=format",
    badge: "Vintage Style",
    stock: 28,
    brand: "Marshall",
    colors: ["Black", "Brown"],
    features: ["Bluetooth", "Multi-Host Function", "Analog Controls", "HDMI Input"]
  },
  {
    id: 48,
    title: "Shure SM7B Microphone",
    price: 399.00,
    originalPrice: 429.00,
    discountPercentage: 7,
    category: "Audio",
    subCategory: "Microphones",
    description: "Professional dynamic microphone for podcasting and vocal recording. Broadcast standard.",
    rating: 4.9,
    reviews: 1654,
    image: "https://images.unsplash.com/photo-1589909615862-2787b7f77d9e?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1589909615862-2787b7f77d9e?w=300&auto=format",
    badge: "Pro Audio",
    stock: 19,
    brand: "Shure",
    colors: ["Black"],
    features: ["Dynamic Cartridge", "Wide Frequency Response", "Humming Coil", "Air Suspension Shock"]
  },
  {
    id: 49,
    title: "Ralph Lauren Polo Shirt",
    price: 89.99,
    originalPrice: 105.00,
    discountPercentage: 14,
    category: "Fashion",
    subCategory: "Clothing",
    description: "Classic polo shirt with embroidered pony. Timeless style in premium cotton pique.",
    rating: 4.7,
    reviews: 5432,
    image: "https://images.unsplash.com/photo-1598033129893-4075f5918e8b?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1598033129893-4075f5918e8b?w=300&auto=format",
    badge: "Classic",
    stock: 78,
    brand: "Ralph Lauren",
    colors: ["Navy", "White", "Black", "Red", "Green"],
    features: ["Premium Cotton", "Embroidered Pony", "Ribbed Collar", "Pearl Buttons"]
  },
  {
    id: 50,
    title: "Herman Miller Aeron Chair",
    price: 1495.00,
    originalPrice: 1695.00,
    discountPercentage: 12,
    category: "Office",
    subCategory: "Furniture",
    description: "Iconic ergonomic office chair with PostureFit SL support and 8Z Pellicle suspension.",
    rating: 4.9,
    reviews: 1234,
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600&auto=format",
    thumbnail: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=300&auto=format",
    badge: "Ergonomic",
    stock: 8,
    brand: "Herman Miller",
    colors: ["Black", "Graphite", "Mineral"],
    features: ["PostureFit SL", "8Z Pellicle", "Adjustable Arms", "Tilt Limiter"]
  },
  // Row 13 - Smart Home & Security (6 products)
{
  id: 51,
  title: "Google Nest Hub Max",
  price: 229.99,
  originalPrice: 249.99,
  discountPercentage: 8,
  category: "Smart Home",
  subCategory: "Smart Displays",
  description: "10-inch smart display with Google Assistant, video calling, and motion sense. Control your smart home and stream content.",
  rating: 4.7,
  reviews: 3456,
  image: "https://images.unsplash.com/photo-1558088458-b84d5b9f5b8f?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1558088458-b84d5b9f5b8f?w=300&auto=format",
  badge: "Smart Choice",
  stock: 34,
  brand: "Google",
  colors: ["Chalk", "Charcoal"],
  features: ["Google Assistant", "10-inch Display", "Video Calling", "Motion Sense"]
},
{
  id: 52,
  title: "Ring Video Doorbell Pro 2",
  price: 249.99,
  originalPrice: 279.99,
  discountPercentage: 11,
  category: "Smart Home",
  subCategory: "Security",
  description: "Smart video doorbell with 3D motion detection, head-to-toe video, and Alexa greetings. Enhanced security for your home.",
  rating: 4.8,
  reviews: 2876,
  image: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=300&auto=format",
  badge: "Top Security",
  stock: 23,
  brand: "Ring",
  colors: ["Satin Nickel", "Venetian Bronze"],
  features: ["3D Motion Detection", "Head-to-Toe Video", "Alexa Greetings", "Night Vision"]
},
{
  id: 53,
  title: "Philips Hue White & Color Ambiance",
  price: 79.99,
  originalPrice: 99.99,
  discountPercentage: 20,
  category: "Smart Home",
  subCategory: "Lighting",
  description: "Smart LED light bulb with 16 million colors and white light. Control with voice or app, set schedules and routines.",
  rating: 4.8,
  reviews: 5678,
  image: "https://images.unsplash.com/photo-1573060220290-5a7c5d9b7c7b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1573060220290-5a7c5d9b7c7b?w=300&auto=format",
  badge: "Best Value",
  stock: 156,
  brand: "Philips Hue",
  colors: ["White"],
  features: ["16 Million Colors", "Voice Control", "Schedules", "Bluetooth & Bridge"]
},
{
  id: 54,
  title: "August Wi-Fi Smart Lock",
  price: 199.99,
  originalPrice: 229.99,
  discountPercentage: 13,
  category: "Smart Home",
  subCategory: "Security",
  description: "Smart lock with built-in Wi-Fi, auto-lock/unlock, and voice control. Grant access to guests remotely.",
  rating: 4.6,
  reviews: 1987,
  image: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=300&auto=format",
  badge: "Smart Security",
  stock: 34,
  brand: "August",
  colors: ["Silver", "Dark Gray"],
  features: ["Built-in Wi-Fi", "Auto-Lock/Unlock", "Voice Control", "Remote Access"]
},
{
  id: 55,
  title: "Arlo Pro 4 Spotlight Camera",
  price: 199.99,
  originalPrice: 229.99,
  discountPercentage: 13,
  category: "Smart Home",
  subCategory: "Security",
  description: "Wireless security camera with 2K HDR, color night vision, and built-in spotlight. No hub required.",
  rating: 4.8,
  reviews: 3245,
  image: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1558001373-7b93ee48ffa0?w=300&auto=format",
  badge: "Top Rated",
  stock: 28,
  brand: "Arlo",
  colors: ["White"],
  features: ["2K HDR", "Color Night Vision", "Built-in Spotlight", "Wireless"]
},
{
  id: 56,
  title: "Ecobee SmartThermostat",
  price: 249.99,
  originalPrice: 279.99,
  discountPercentage: 11,
  category: "Smart Home",
  subCategory: "Climate",
  description: "Smart thermostat with built-in Alexa, voice control, and room sensors. Save energy and stay comfortable.",
  rating: 4.8,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1567924015112-1238cb5d3f3f?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1567924015112-1238cb5d3f3f?w=300&auto=format",
  badge: "Energy Saver",
  stock: 31,
  brand: "Ecobee",
  colors: ["Black"],
  features: ["Built-in Alexa", "Room Sensors", "Voice Control", "Energy Reports"]
},

// Row 14 - Pet Supplies (6 products)
{
  id: 57,
  title: "Furbo 360° Dog Camera",
  price: 249.99,
  originalPrice: 299.99,
  discountPercentage: 17,
  category: "Pets",
  subCategory: "Cameras",
  description: "360° rotating dog camera with treat tossing, 2-way audio, and barking alerts. Keep an eye on your pup.",
  rating: 4.7,
  reviews: 2876,
  image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format",
  badge: "Pet Favorite",
  stock: 23,
  brand: "Furbo",
  colors: ["White"],
  features: ["360° Rotation", "Treat Tossing", "2-Way Audio", "Barking Alerts"]
},
{
  id: 58,
  title: "Litter-Robot 4",
  price: 699.00,
  originalPrice: 749.00,
  discountPercentage: 7,
  category: "Pets",
  subCategory: "Litter Boxes",
  description: "Automatic self-cleaning litter box with odor control and waste drawer. Connects to app for monitoring.",
  rating: 4.8,
  reviews: 1654,
  image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format",
  badge: "Innovation",
  stock: 12,
  brand: "Whisker",
  colors: ["White", "Black"],
  features: ["Self-Cleaning", "Odor Control", "App Monitoring", "Large Waste Drawer"]
},
{
  id: 59,
  title: "PetSafe Automatic Feeder",
  price: 89.99,
  originalPrice: 109.99,
  discountPercentage: 18,
  category: "Pets",
  subCategory: "Feeders",
  description: "Programmable automatic pet feeder with portion control and up to 6 meals per day. Battery backup included.",
  rating: 4.6,
  reviews: 5432,
  image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format",
  badge: "Best Seller",
  stock: 78,
  brand: "PetSafe",
  colors: ["Gray"],
  features: ["6 Meals/Day", "Portion Control", "Battery Backup", "Easy Clean"]
},
{
  id: 60,
  title: "Furhaven Pet Bed",
  price: 49.99,
  originalPrice: 69.99,
  discountPercentage: 29,
  category: "Pets",
  subCategory: "Beds",
  description: "Orthopedic foam pet bed with removable, machine-washable cover. Provides joint relief and comfort.",
  rating: 4.8,
  reviews: 8765,
  image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format",
  badge: "Comfort",
  stock: 145,
  brand: "Furhaven",
  colors: ["Gray", "Brown", "Blue"],
  features: ["Orthopedic Foam", "Machine Washable", "Non-Skid Bottom", "Waterproof Liner"]
},
{
  id: 61,
  title: "Outward Hound Life Jacket",
  price: 34.99,
  originalPrice: 44.99,
  discountPercentage: 22,
  category: "Pets",
  subCategory: "Safety",
  description: "Dog life jacket with rescue handle, bright colors, and adjustable straps. Ensures safety during water activities.",
  rating: 4.7,
  reviews: 3210,
  image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format",
  badge: "Safety First",
  stock: 67,
  brand: "Outward Hound",
  colors: ["Orange", "Red", "Blue"],
  features: ["Rescue Handle", "High Visibility", "Adjustable Straps", "Floatation"]
},
{
  id: 62,
  title: "Catit Pixi Fountain",
  price: 39.99,
  originalPrice: 49.99,
  discountPercentage: 20,
  category: "Pets",
  subCategory: "Water Fountains",
  description: "Stainless steel water fountain with triple-action filtration and LED light. Encourages cats to drink more.",
  rating: 4.7,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&auto=format",
  badge: "Hydration",
  stock: 54,
  brand: "Catit",
  colors: ["White"],
  features: ["Triple Filtration", "LED Light", "Stainless Steel", "Quiet Pump"]
},

// Row 15 - Tools & Home Improvement (6 products)
{
  id: 63,
  title: "DeWalt 20V Drill Combo Kit",
  price: 199.99,
  originalPrice: 249.99,
  discountPercentage: 20,
  category: "Tools",
  subCategory: "Power Tools",
  description: "20V cordless drill and impact driver combo kit with batteries and charger. Perfect for DIY and professional use.",
  rating: 4.9,
  reviews: 6543,
  image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&auto=format",
  badge: "Pro Choice",
  stock: 34,
  brand: "DeWalt",
  colors: ["Yellow/Black"],
  features: ["20V Max", "2-Tool Kit", "Brushess Motor", "LED Light"]
},
{
  id: 64,
  title: "Bosch Laser Distance Measurer",
  price: 129.99,
  originalPrice: 159.99,
  discountPercentage: 19,
  category: "Tools",
  subCategory: "Measuring",
  description: "Laser distance measurer with 165ft range, digital display, and multiple measurement modes. Accuracy within 1/16 inch.",
  rating: 4.8,
  reviews: 1876,
  image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&auto=format",
  badge: "Precision",
  stock: 42,
  brand: "Bosch",
  colors: ["Blue"],
  features: ["165ft Range", "1/16 inch Accuracy", "Multiple Modes", "Backlit Display"]
},
{
  id: 65,
  title: "Milwaukee M18 Sawzall",
  price: 179.99,
  originalPrice: 199.99,
  discountPercentage: 10,
  category: "Tools",
  subCategory: "Power Tools",
  description: "M18 FUEL reciprocating saw with Redlink intelligence, variable speed, and tool-free blade change.",
  rating: 4.9,
  reviews: 2987,
  image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&auto=format",
  badge: "Heavy Duty",
  stock: 21,
  brand: "Milwaukee",
  colors: ["Red/Black"],
  features: ["M18 FUEL", "Redlink Intelligence", "Tool-Free Blade Change", "Variable Speed"]
},
{
  id: 66,
  title: "Stanley Tool Set",
  price: 89.99,
  originalPrice: 119.99,
  discountPercentage: 25,
  category: "Tools",
  subCategory: "Hand Tools",
  description: "85-piece home repair tool set with hammer, pliers, screwdrivers, wrenches, and sockets. Everything you need.",
  rating: 4.7,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&auto=format",
  badge: "Complete Set",
  stock: 67,
  brand: "Stanley",
  colors: ["Black/Yellow"],
  features: ["85 Pieces", "Organized Case", "Chrome Vanadium", "Lifetime Warranty"]
},
{
  id: 67,
  title: "Ryobi 18V Leaf Blower",
  price: 99.99,
  originalPrice: 129.99,
  discountPercentage: 23,
  category: "Outdoor",
  subCategory: "Lawn Care",
  description: "Cordless leaf blower with 18V battery, variable speed trigger, and 100+ mph airspeed. Lightweight and quiet.",
  rating: 4.6,
  reviews: 2876,
  image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&auto=format",
  badge: "Yard Essential",
  stock: 45,
  brand: "Ryobi",
  colors: ["Green"],
  features: ["100+ mph", "Variable Speed", "Lightweight", "Battery Included"]
},
{
  id: 68,
  title: "Black+Decker Hedge Trimmer",
  price: 79.99,
  originalPrice: 99.99,
  discountPercentage: 20,
  category: "Outdoor",
  subCategory: "Lawn Care",
  description: "Corded electric hedge trimmer with 22-inch dual-action blades and ergonomic grip. Easy hedge maintenance.",
  rating: 4.6,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=300&auto=format",
  badge: "Garden Tool",
  stock: 38,
  brand: "Black+Decker",
  colors: ["Orange"],
  features: ["22-inch Blades", "Dual-Action", "Electric", "Ergonomic Grip"]
},

// Row 16 - Automotive (6 products)
{
  id: 69,
  title: "Dash Cam 4K",
  price: 129.99,
  originalPrice: 169.99,
  discountPercentage: 24,
  category: "Automotive",
  subCategory: "Electronics",
  description: "4K UHD dash cam with night vision, WiFi, GPS, and loop recording. Captures every moment on the road.",
  rating: 4.7,
  reviews: 3456,
  image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=300&auto=format",
  badge: "Safety",
  stock: 52,
  brand: "Vantrue",
  colors: ["Black"],
  features: ["4K Recording", "Night Vision", "WiFi & GPS", "Loop Recording"]
},
{
  id: 70,
  title: "NOCO Boost Plus Jump Starter",
  price: 99.99,
  originalPrice: 129.99,
  discountPercentage: 23,
  category: "Automotive",
  subCategory: "Emergency",
  description: "1000-amp portable jump starter for gas and diesel engines. Also charges USB devices and includes LED light.",
  rating: 4.9,
  reviews: 8765,
  image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=300&auto=format",
  badge: "Essential",
  stock: 87,
  brand: "NOCO",
  colors: ["Red/Black"],
  features: ["1000 Amps", "USB Charging", "LED Light", "Spark-Proof"]
},
{
  id: 71,
  title: "Michelin Wiper Blades",
  price: 29.99,
  originalPrice: 39.99,
  discountPercentage: 25,
  category: "Automotive",
  subCategory: "Maintenance",
  description: "Premium beam wiper blades with built-in wear indicator and weather shield. All-season performance.",
  rating: 4.8,
  reviews: 5432,
  image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=300&auto=format",
  badge: "Visibility",
  stock: 134,
  brand: "Michelin",
  colors: ["Black"],
  features: ["All-Season", "Wear Indicator", "Weather Shield", "Easy Install"]
},
{
  id: 72,
  title: "Car Vacuum Cleaner",
  price: 49.99,
  originalPrice: 69.99,
  discountPercentage: 29,
  category: "Automotive",
  subCategory: "Cleaning",
  description: "High-power handheld car vacuum with HEPA filter, crevice tools, and 16ft cord. Keeps your car spotless.",
  rating: 4.6,
  reviews: 3210,
  image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=300&auto=format",
  badge: "Clean Machine",
  stock: 65,
  brand: "Armor All",
  colors: ["Black"],
  features: ["HEPA Filter", "16ft Cord", "Crevice Tools", "Washable Filter"]
},
{
  id: 73,
  title: "Tire Inflator Portable",
  price: 59.99,
  originalPrice: 79.99,
  discountPercentage: 25,
  category: "Automotive",
  subCategory: "Emergency",
  description: "12V DC portable air compressor with digital display, auto shut-off, and LED light. Inflates tires quickly.",
  rating: 4.7,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=300&auto=format",
  badge: "Road Trip",
  stock: 73,
  brand: "EPAuto",
  colors: ["Black"],
  features: ["Digital Display", "Auto Shut-Off", "LED Light", "Multiple Nozzles"]
},
{
  id: 74,
  title: "Car Cover Waterproof",
  price: 89.99,
  originalPrice: 119.99,
  discountPercentage: 25,
  category: "Automotive",
  subCategory: "Protection",
  description: "All-weather car cover with 6-layer protection, windproof straps, and storage bag. Fits most sedans.",
  rating: 4.6,
  reviews: 1876,
  image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=300&auto=format",
  badge: "Protection",
  stock: 42,
  brand: "Kayme",
  colors: ["Silver"],
  features: ["6-Layer Protection", "Waterproof", "Windproof Straps", "Storage Bag"]
},

// Row 17 - Baby & Kids (6 products)
{
  id: 75,
  title: "UPPAbaby Vista V2 Stroller",
  price: 999.99,
  originalPrice: 1099.99,
  discountPercentage: 9,
  category: "Baby",
  subCategory: "Strollers",
  description: "Premium modular stroller that converts from single to double. Includes bassinet, toddler seat, and rain shield.",
  rating: 4.9,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=300&auto=format",
  badge: "Luxury",
  stock: 8,
  brand: "UPPAbaby",
  colors: ["Jake", "Gwen", "Cruz"],
  features: ["Converts to Double", "Includes Bassinet", "Large Storage", "All-Wheel Suspension"]
},
{
  id: 76,
  title: "Baby Brezza Formula Pro",
  price: 199.99,
  originalPrice: 229.99,
  discountPercentage: 13,
  category: "Baby",
  subCategory: "Feeding",
  description: "Automatic formula dispenser that mixes and warms bottles at the touch of a button. Perfect for nighttime feedings.",
  rating: 4.8,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=300&auto=format",
  badge: "Parent Saver",
  stock: 23,
  brand: "Baby Brezza",
  colors: ["White"],
  features: ["Automatic Mixing", "Warms Formula", "10 Temperature Settings", "Easy Clean"]
},
{
  id: 77,
  title: "Graco 4Ever Car Seat",
  price: 299.99,
  originalPrice: 349.99,
  discountPercentage: 14,
  category: "Baby",
  subCategory: "Car Seats",
  description: "4-in-1 convertible car seat grows from infant to booster. 10-position headrest and SafeAdjust harness.",
  rating: 4.9,
  reviews: 6543,
  image: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=300&auto=format",
  badge: "Grows with Baby",
  stock: 31,
  brand: "Graco",
  colors: ["Gotham", "Carlson"],
  features: ["4-in-1 Design", "10-Position Headrest", "SafeAdjust Harness", "Steel Frame"]
},
{
  id: 78,
  title: "Owlet Smart Sock 3",
  price: 299.99,
  originalPrice: 329.99,
  discountPercentage: 9,
  category: "Baby",
  subCategory: "Monitoring",
  description: "Smart baby monitor that tracks heart rate and oxygen levels. Sends alerts to your phone if readings change.",
  rating: 4.7,
  reviews: 2987,
  image: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=300&auto=format",
  badge: "Peace of Mind",
  stock: 17,
  brand: "Owlet",
  colors: ["Gray"],
  features: ["Heart Rate Tracking", "Oxygen Monitoring", "Base Station", "App Alerts"]
},
{
  id: 79,
  title: "Hatch Baby Rest Sound Machine",
  price: 69.99,
  originalPrice: 89.99,
  discountPercentage: 22,
  category: "Baby",
  subCategory: "Sleep",
  description: "Sound machine, night light, and time-to-rise alert in one. Control from your phone via app.",
  rating: 4.8,
  reviews: 5432,
  image: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=300&auto=format",
  badge: "Sleep Helper",
  stock: 87,
  brand: "Hatch",
  colors: ["White", "Gray", "Pink", "Blue"],
  features: ["Sound Machine", "Night Light", "Time-to-Rise", "App Control"]
},
{
  id: 80,
  title: "Joolz Aer Stroller",
  price: 449.99,
  originalPrice: 499.99,
  discountPercentage: 10,
  category: "Baby",
  subCategory: "Strollers",
  description: "Ultra-compact travel stroller with one-hand fold, carry strap, and extendable canopy. FAA approved for carry-on.",
  rating: 4.8,
  reviews: 1654,
  image: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1593510987040-123d9d9a2a4b?w=300&auto=format",
  badge: "Travel Ready",
  stock: 19,
  brand: "Joolz",
  colors: ["Black", "Olive"],
  features: ["One-Hand Fold", "Carry Strap", "FAA Approved", "Extendable Canopy"]
},

// Row 18 - Health & Wellness (6 products)
{
  id: 81,
  title: "Theragun Elite",
  price: 399.99,
  originalPrice: 449.99,
  discountPercentage: 11,
  category: "Health",
  subCategory: "Massage",
  description: "Advanced percussion massage device with OLED screen, Bluetooth, and guided routines. Relieves muscle tension.",
  rating: 4.8,
  reviews: 3456,
  image: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=300&auto=format",
  badge: "Recovery",
  stock: 23,
  brand: "Therabody",
  colors: ["Black", "White"],
  features: ["OLED Screen", "Bluetooth", "Guided Routines", "QuietForce Technology"]
},
{
  id: 82,
  title: "Fitbit Charge 6",
  price: 159.99,
  originalPrice: 179.99,
  discountPercentage: 11,
  category: "Health",
  subCategory: "Fitness Trackers",
  description: "Advanced fitness tracker with heart rate monitoring, GPS, and 7-day battery. Tracks sleep and activity.",
  rating: 4.7,
  reviews: 5678,
  image: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=300&auto=format",
  badge: "Fitness",
  stock: 54,
  brand: "Fitbit",
  colors: ["Black", "Blue", "Pink"],
  features: ["Heart Rate", "Built-in GPS", "Sleep Tracking", "7-Day Battery"]
},
{
  id: 83,
  title: "Omron Blood Pressure Monitor",
  price: 69.99,
  originalPrice: 89.99,
  discountPercentage: 22,
  category: "Health",
  subCategory: "Monitoring",
  description: "Upper arm blood pressure monitor with advanced accuracy and irregular heartbeat detection. Stores readings.",
  rating: 4.9,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=300&auto=format",
  badge: "Health Essential",
  stock: 98,
  brand: "Omron",
  colors: ["White"],
  features: ["Advanced Accuracy", "Irregular Heartbeat", "100 Readings", "Cuff Included"]
},
{
  id: 84,
  title: "Weighted Blanket",
  price: 89.99,
  originalPrice: 119.99,
  discountPercentage: 25,
  category: "Health",
  subCategory: "Sleep",
  description: "15lb weighted blanket with glass beads and bamboo cover. Promotes deeper sleep and reduces anxiety.",
  rating: 4.8,
  reviews: 6543,
  image: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=300&auto=format",
  badge: "Calm Sleep",
  stock: 67,
  brand: "YnM",
  colors: ["Gray", "Blue", "Green"],
  features: ["15lb Weight", "Glass Beads", "Removable Cover", "Breathable Fabric"]
},
{
  id: 85,
  title: "TheraFace Pro",
  price: 399.99,
  originalPrice: 449.99,
  discountPercentage: 11,
  category: "Beauty",
  subCategory: "Skincare Tools",
  description: "4-in-1 facial treatment device with microcurrent, LED light therapy, and percussion massage. Professional results.",
  rating: 4.7,
  reviews: 1876,
  image: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=300&auto=format",
  badge: "Skincare",
  stock: 14,
  brand: "Therabody",
  colors: ["White"],
  features: ["Microcurrent", "LED Light Therapy", "Percussion", "Interchangeable Heads"]
},
{
  id: 86,
  title: "Meditation Cushion Set",
  price: 59.99,
  originalPrice: 79.99,
  discountPercentage: 25,
  category: "Health",
  subCategory: "Meditation",
  description: "Set of meditation cushions including zafu and zabuton. Buckwheat hull filling for comfortable posture.",
  rating: 4.8,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1624726175511-19b9bafb4b8d?w=300&auto=format",
  badge: "Mindfulness",
  stock: 45,
  brand: "Florensi",
  colors: ["Purple", "Blue", "Gray"],
  features: ["Zafu & Zabuton", "Buckwheat Hull", "Removable Cover", "Handmade"]
},

// Row 19 - Office & Desk Accessories (6 products)
{
  id: 87,
  title: "Secretlab Titan Evo",
  price: 549.99,
  originalPrice: 599.99,
  discountPercentage: 8,
  category: "Office",
  subCategory: "Chairs",
  description: "Premium ergonomic gaming chair with 4-way adjustable lumbar support and magnetic memory foam head pillow.",
  rating: 4.9,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=300&auto=format",
  badge: "Ergonomic",
  stock: 18,
  brand: "Secretlab",
  colors: ["Black", "Stealth", "Cookies & Cream"],
  features: ["4-Way Lumbar", "Magnetic Pillow", "Multi-Tilt Mechanism", "Pebble Leather"]
},
{
  id: 88,
  title: "Fully Jarvis Standing Desk",
  price: 599.99,
  originalPrice: 699.99,
  discountPercentage: 14,
  category: "Office",
  subCategory: "Desks",
  description: "Electric height-adjustable standing desk with programmable presets and bamboo top. Improves posture and health.",
  rating: 4.8,
  reviews: 2876,
  image: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=300&auto=format",
  badge: "Stand Up",
  stock: 12,
  brand: "Fully",
  colors: ["Bamboo"],
  features: ["Electric Lift", "Programmable", "Bamboo Top", "Sturdy Frame"]
},
{
  id: 89,
  title: "Logitech MX Master 3S",
  price: 99.99,
  originalPrice: 129.99,
  discountPercentage: 23,
  category: "Electronics",
  subCategory: "Mice",
  description: "Advanced wireless mouse with 8K DPI, quiet clicks, and MagSpeed scrolling. Ergonomic design for all-day comfort.",
  rating: 4.9,
  reviews: 8765,
  image: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=300&auto=format",
  badge: "Productivity",
  stock: 67,
  brand: "Logitech",
  colors: ["Graphite", "Pale Gray"],
  features: ["8K DPI", "Quiet Clicks", "MagSpeed Scroll", "Multi-Device"]
},
{
  id: 90,
  title: "Keychron Q1 Pro",
  price: 199.99,
  originalPrice: 229.99,
  discountPercentage: 13,
  category: "Electronics",
  subCategory: "Keyboards",
  description: "Wireless mechanical keyboard with QMK/VIA support, double-shot PBT keycaps, and premium aluminum case.",
  rating: 4.8,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=300&auto=format",
  badge: "Mechanical",
  stock: 32,
  brand: "Keychron",
  colors: ["Carbon Black", "Silver Gray"],
  features: ["Wireless", "QMK/VIA", "Hot-Swappable", "Aluminum Case"]
},
{
  id: 91,
  title: "BenQ ScreenBar Plus",
  price: 109.99,
  originalPrice: 129.99,
  discountPercentage: 15,
  category: "Office",
  subCategory: "Lighting",
  description: "Monitor-mounted LED lamp with auto-dimming and desktop controller. Reduces eye strain and saves desk space.",
  rating: 4.8,
  reviews: 3456,
  image: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=300&auto=format",
  badge: "Eye Care",
  stock: 43,
  brand: "BenQ",
  colors: ["Black"],
  features: ["Auto-Dimming", "Desktop Controller", "Monitor Mount", "Eye-Care Technology"]
},
{
  id: 92,
  title: "Rocketbook Fusion",
  price: 29.99,
  originalPrice: 39.99,
  discountPercentage: 25,
  category: "Office",
  subCategory: "Notebooks",
  description: "Reusable smart notebook with 42 pages, cloud integration, and Pilot FriXion pen. Upload notes to the cloud.",
  rating: 4.7,
  reviews: 6543,
  image: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1596079890744-c1a0462d0975?w=300&auto=format",
  badge: "Eco-Friendly",
  stock: 98,
  brand: "Rocketbook",
  colors: ["Black", "Blue", "Green"],
  features: ["Reusable", "Cloud Integration", "42 Pages", "Pen Included"]
},
// Row 20 - Musical Instruments (6 products)
{
  id: 93,
  title: "Yamaha P-125 Digital Piano",
  price: 699.99,
  originalPrice: 799.99,
  discountPercentage: 12,
  category: "Musical Instruments",
  subCategory: "Pianos",
  description: "88-key weighted action digital piano with PureCF sound engine and built-in speakers. Perfect for home practice.",
  rating: 4.9,
  reviews: 1876,
  image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&auto=format",
  badge: "Musician",
  stock: 14,
  brand: "Yamaha",
  colors: ["Black"],
  features: ["88 Weighted Keys", "PureCF Sound", "Built-in Speakers", "USB to Host"]
},
{
  id: 94,
  title: "Fender Player Stratocaster",
  price: 799.99,
  originalPrice: 899.99,
  discountPercentage: 11,
  category: "Musical Instruments",
  subCategory: "Guitars",
  description: "Electric guitar with alder body, maple neck, and Player Series pickups. Iconic sound and feel.",
  rating: 4.8,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&auto=format",
  badge: "Classic",
  stock: 9,
  brand: "Fender",
  colors: ["Black", "Sunburst", "Polar White"],
  features: ["Alder Body", "Maple Neck", "Player Pickups", "2-Point Tremolo"]
},
{
  id: 95,
  title: "Focusrite Scarlett 2i2",
  price: 169.99,
  originalPrice: 199.99,
  discountPercentage: 15,
  category: "Musical Instruments",
  subCategory: "Audio Interfaces",
  description: "USB audio interface with two mic preamps, high-quality converters, and bundled software. Perfect for home studio.",
  rating: 4.9,
  reviews: 4321,
  image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&auto=format",
  badge: "Studio",
  stock: 38,
  brand: "Focusrite",
  colors: ["Red"],
  features: ["2 Mic Preamps", "24-bit/192kHz", "Direct Monitoring", "Bundled Software"]
},
{
  id: 96,
  title: "Roland TD-07KV V-Drums",
  price: 899.99,
  originalPrice: 999.99,
  discountPercentage: 10,
  category: "Musical Instruments",
  subCategory: "Drums",
  description: "Compact electronic drum kit with mesh heads, 25 preset kits, and Bluetooth connectivity. Quiet practice.",
  rating: 4.8,
  reviews: 1234,
  image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&auto=format",
  badge: "Practice",
  stock: 7,
  brand: "Roland",
  colors: ["Black"],
  features: ["Mesh Heads", "25 Kits", "Bluetooth", "Built-in Coach"]
},
{
  id: 97,
  title: "Shure SM58-LC",
  price: 99.99,
  originalPrice: 129.99,
  discountPercentage: 23,
  category: "Musical Instruments",
  subCategory: "Microphones",
  description: "Professional vocal microphone with cardioid pattern and tailored frequency response. Industry standard.",
  rating: 4.9,
  reviews: 8765,
  image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&auto=format",
  badge: "Legendary",
  stock: 87,
  brand: "Shure",
  colors: ["Silver"],
  features: ["Cardioid Pattern", "Frequency Tailored", "Pneumatic Shock Mount", "Built-in Pop Filter"]
},
{
  id: 98,
  title: "Korg Minilogue XD",
  price: 649.99,
  originalPrice: 699.99,
  discountPercentage: 7,
  category: "Musical Instruments",
  subCategory: "Synthesizers",
  description: "Polyphonic analog synthesizer with digital effects, sequencer, and user-customizable engine. Powerful sound design.",
  rating: 4.8,
  reviews: 1654,
  image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=300&auto=format",
  badge: "Synth",
  stock: 13,
  brand: "Korg",
  colors: ["Black", "Silver"],
  features: ["4-Voice Poly", "Digital Effects", "Sequencer", "User Oscillator"]
},

// Row 21 - Art & Craft (6 products)
{
  id: 99,
  title: "Cricut Maker 3",
  price: 399.99,
  originalPrice: 449.99,
  discountPercentage: 11,
  category: "Crafts",
  subCategory: "Cutting Machines",
  description: "Smart cutting machine that cuts 300+ materials without a mat. Perfect for DIY projects and crafts.",
  rating: 4.8,
  reviews: 3210,
  image: "https://images.unsplash.com/photo-1567721913486-6585f069b332?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1567721913486-6585f069b332?w=300&auto=format",
  badge: "Creative",
  stock: 19,
  brand: "Cricut",
  colors: ["Blue"],
  features: ["Cuts 300+ Materials", "No Mat Needed", "Bluetooth", "Double Cut"]
},
{
  id: 100,
  title: "Wacom Intuos Pro Medium",
  price: 349.99,
  originalPrice: 399.99,
  discountPercentage: 12,
  category: "Electronics",
  subCategory: "Drawing Tablets",
  description: "Professional pen tablet with 8192 pressure sensitivity, multi-touch, and customizable ExpressKeys. For digital artists.",
  rating: 4.9,
  reviews: 2341,
  image: "https://images.unsplash.com/photo-1567721913486-6585f069b332?w=600&auto=format",
  thumbnail: "https://images.unsplash.com/photo-1567721913486-6585f069b332?w=300&auto=format",
  badge: "Artist Choice",
  stock: 22,
  brand: "Wacom",
  colors: ["Black"],
  features: ["8192 Pressure", "Multi-Touch", "ExpressKeys", "Bluetooth"]
}
];